### Send POST request with json body
POST http://localhost:8080/addCartItem?cartId=2
Content-Type: application/json
//Authorization: {{authToken}}
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWFwbGUiLCJpZCI6MSwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc0NzIxOTA0MCwiZXhwIjoxNzQ3MjE5NjQwfQ.vp-JtgrX_1QXefMXiyoRcLNHA_tsETJ_LH6G3pd2qTo

{

  "productId": 9,
  "quantity": 2

}