### Send POST request with json body
POST http://localhost:8080/cartSummary/2
Content-Type: application/json
//Authorization: {{authToken}}
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWFwbGUiLCJpZCI6MSwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc0NzMxOTgwNCwiZXhwIjoxNzQ3MzIwNDA0fQ.DNAvO6r9OjLSWzV8b7jra8UHd25mzB3l39s2rthOtZU

