### Send POST request with json body
POST http://localhost:8080/deleteCartItems
Content-Type: application/json
//Authorization: {{authToken}}
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWFwbGUiLCJpZCI6MSwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc0NTMwNTEyMywiZXhwIjoxNzQ1MzA1NzIzfQ.vrAbQifGyOkS7JqcqbZ3HuTEnPGjx1SahrKCngnxij0

{

  "cartItemsId":1

}