POST http://localhost:8080/logout
Content-Type: application/x-www-form-urlencoded
Cookie: refresh=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InJlZnJlc2giLCJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjMsInJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzQyNDU1NzIwLCJleHAiOjE3NDI1NDIxMjB9.Vk6ZgeDH69XW8y_z63s4G01ryZUU9ivIfqOGlApoums;