### Send POST request with json body
POST http://localhost:8080/saveProduct
Content-Type: application/json
access:eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYWRtaW4iLCJpZCI6Mywicm9sZSI6IlJPTEVfQURNSU4iLCJpYXQiOjE3NDMwNTQ3NDIsImV4cCI6MTc0MzA1NTM0Mn0.4psJ7e378JRtUmDt28EmW-aYkqILC0TAG9xNKYRY64I
//Authorization: {{authToken}}

{
  "product_name": "일반도자기",
  "description": "일반적인 느낌의 도자기입니다 !",
  "quantity": 8,
  "price": 25000

}